import { BadRequestException } from '@nestjs/common';
import type { ArgumentMetadata } from '@nestjs/common';

import { v4 as uuidv4, v7 as uuidv7 } from 'uuid';

import { UuidParamPipe } from '../uuid-param.pipe.js';

const metadata: ArgumentMetadata = { type: 'param', data: 'id', metatype: String };

describe('UuidParamPipe', () => {
  it.each([
    ['v7 (generated by BaseEntity)', uuidv7()],
    ['v4', uuidv4()],
  ])('should return the id unchanged when it is a UUID %s', async (_label, id) => {
    await expect(UuidParamPipe.transform(id, metadata)).resolves.toBe(id);
  });

  it.each(['abc', '123', '', '0199a1b2-c3d4-7e5f-8a6b-0123456789a'])(
    'should throw BadRequestException with a Vietnamese message when id is "%s"',
    async (id) => {
      const result = UuidParamPipe.transform(id, metadata);

      await expect(result).rejects.toThrow(BadRequestException);
      await expect(result).rejects.toThrow('id không hợp lệ (phải là UUID)');
    },
  );
});
