export const TIKTOK_TABLE_NAMES = {
  integrationUser: 'integration_user',
  bitrixInstallation: 'integration_bitrix_installation',
  configuration: 'integration_configuration',
  configurationHead: 'integration_configuration_head',
  lead: 'integration_lead',
  timeline: 'integration_timeline',
  leadIdentity: 'integration_lead_identity',
  submission: 'integration_submission',
  deal: 'integration_deal',
  dealHistory: 'integration_deal_history',
  dealPollCheckpoint: 'integration_deal_poll_checkpoint',
  assignmentCursor: 'integration_assignment_cursor',
  auditEvent: 'integration_audit_event',
  webhookEvent: 'integration_webhook_event',
  operation: 'integration_operation',
  outbox: 'integration_outbox',
  aggregateLease: 'integration_aggregate_lease',
  campaignDaily: 'integration_campaign_daily',
  reportJob: 'integration_report_job',
  reportRowError: 'integration_report_row_error',
  notification: 'integration_notification',
} as const;
